### ISSUE TITLE
Does not work with latest Magisk

### ISSUE THREAD

**Issue by alien2003** [mithrandir42/cosmo-fs#1]
Official Rooted Android for Cosmo was updated to Magisk 20.4 and the module seems to be broken now.

Still works after manually typing `insmod` and `killall vold`. I'm not  familiar with Magisk and Android development but I can provide any logs you need

**Comment by mithrandir42** [comment]
On my Cosmo the module still works with Magisk 20.4. So I have some questions:
-Has the module been working for you, before the Magisk/Root upgrade?
-Have you already tried to uninstall/reinstall it?
-What is the output running /data/adb/modules/cosmo-fs/service.sh manually from rooted termux session? Does it work then?

**Comment by mithrandir42** [comment]
Some additional thoughts:
I have never tried the module without device protection (password/fingerprint) enabled. So, do you use it with protection? Just guessing, but the "wait user to unlock" loop might wait forever in this case. If so, please try to set as password. Maybe it also helps (just guessing) to remove the lines 17 to 22 from the service.sh script.

**Comment by alien2003** [comment]
>Has the module been working for you, before the Magisk/Root upgrade?
Yes
> Have you already tried to uninstall/reinstall it?
Yes
> What is the output running /data/adb/modules/cosmo-fs/service.sh manually from rooted termux session? Does it work then?
I tried to run it manually, everything works as expected in this case.
> do you use it with protection?
Yes, password and fingerprint. Maybe fingerprint is an issue. If the ROM is brand new and there is no apps installed, module works as expected but if you have a lot of apps installed and running on system boot, seems like it breaks module.

I decided to uninstall this module and stick with proprietary Paragon SAF driver because this module corrupted my /data at some point and as we currently don't have any method to backup Cosmo data I can't test it again

**Comment by mithrandir42** [comment]
After planet computers latest android update, V25 the module seems to work flawless. Before sometimes on startup the vold reinitialization seemed not to happen and one had to run the service script manually. After the android update this seems to be stable.
